# Generated by Django 5.1.5 on 2025-07-03 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='page',
            options={'managed': True, 'ordering': ['order', 'title'], 'verbose_name': 'Página', 'verbose_name_plural': 'Paginas'},
        ),
        migrations.AddField(
            model_name='page',
            name='order',
            field=models.SmallIntegerField(default=0, verbose_name='Orden'),
        ),
    ]
